head="<!DOCTYPE html>\n<html>\n<head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'></head>\n"
title="<body>\n<h1 style='text-align: center; color:red;'>Tâches de cette semaine</h1>\n<ul style='text-align: center; display: flex; flex-direction: column; align-items: center;'>\n"

ul_content="<li>{person}: {task}</li>\n"

form_start="</ul><br>\n<form action='/rotate' method='POST' style='text-align: center;'>\n"
form_n_rotations="<label>Nombre de tours :</label><br>\n<input type='number' name='n_rotations' value='1' min='1' max='{rotations_max}' step='1' /><br>\n"
form_key="<label>Clé :</label><br>\n<input type='password' name='key' /><br><br>\n"
form_submit="<input style='background-color: #04AA6D; color: white; cursor: pointer; border: 2px solid gray; border-radius: 4px;' type='submit' value='Tourner la roue' />\n</form>\n</body>\n</html>"